# Generated by Django 4.2 on 2025-11-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_label_alter_item_category_alter_item_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Imagen que se mostrará en la página principal. Si está vacía, se usará la imagen principal.', null=True, upload_to='products/previews/', verbose_name='Imagen de Previsualización'),
        ),
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, help_text='Video corto del producto (máximo 10 segundos)', null=True, upload_to='products/videos/', verbose_name='Video del Producto'),
        ),
    ]
