# Generated by Django 4.2 on 2025-11-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_preview_image_item_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
